# Generated by Django 3.0.8 on 2020-07-16 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryName', models.CharField(max_length=50)),
                ('categoryTitle', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='')),
                ('isActive', models.BooleanField()),
            ],
            options={
                'db_table': 'ServiceCategories',
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serviceTitle', models.CharField(max_length=50)),
                ('descriptionTitle', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('technologies', models.CharField(max_length=150)),
                ('image1', models.ImageField(upload_to='')),
                ('image2', models.ImageField(blank=True, null=True, upload_to=None)),
                ('image3', models.ImageField(blank=True, null=True, upload_to=None)),
                ('contactTitle', models.CharField(max_length=50)),
                ('filedTitle', models.CharField(max_length=50)),
                ('contactAddress', models.CharField(max_length=100)),
                ('contactPhone', models.BigIntegerField()),
                ('contactEmail', models.EmailField(max_length=150)),
                ('isActive', models.BooleanField()),
            ],
            options={
                'db_table': 'Services',
            },
        ),
    ]
