# Generated by Django 3.0.8 on 2020-07-16 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0004_auto_20200716_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicecategories',
            name='image',
            field=models.ImageField(upload_to='uploads/categories'),
        ),
        migrations.AlterField(
            model_name='services',
            name='image1',
            field=models.ImageField(upload_to='static/uploads/services'),
        ),
        migrations.AlterField(
            model_name='services',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='static/uploads/services'),
        ),
        migrations.AlterField(
            model_name='services',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='static/uploads/services'),
        ),
    ]
