# Generated by Django 3.0.8 on 2020-07-16 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0005_auto_20200716_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicecategories',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
