# Generated by Django 3.0.8 on 2020-07-16 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0007_auto_20200716_1647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicecategories',
            name='image',
        ),
        migrations.CreateModel(
            name='ServiceSubCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/uploads/categories')),
                ('isActive', models.BooleanField()),
                ('categoryID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.ServiceCategories')),
            ],
            options={
                'db_table': 'ServiceSubCategories',
            },
        ),
    ]
