# Generated by Django 3.0.8 on 2020-07-16 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0008_auto_20200716_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicesubcategories',
            name='subCategoryTitle',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
