# Generated by Django 3.0.8 on 2020-07-16 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0009_servicesubcategories_subcategorytitle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicesubcategories',
            old_name='categoryID',
            new_name='category',
        ),
    ]
