# Generated by Django 3.0.8 on 2020-07-16 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0010_auto_20200716_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicesubcategories',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategory', to='adminpanel.ServiceCategories'),
        ),
    ]
