# Generated by Django 3.0.6 on 2020-07-23 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0011_auto_20200716_1751'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientLogo', models.ImageField(upload_to='static/uploads/clients')),
                ('isActive', models.BooleanField()),
            ],
            options={
                'db_table': 'Clients',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='static/uploads/team')),
                ('isActive', models.BooleanField()),
            ],
            options={
                'db_table': 'Team',
            },
        ),
    ]
