# Generated by Django 3.0.6 on 2020-07-24 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0012_clients_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='industry',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='adminpanel.ServiceSubCategories'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicesubcategories',
            name='description',
            field=models.CharField(default='sample', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicesubcategories',
            name='features',
            field=models.CharField(default='sample 1, sample 2, sample 3', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='servicesubcategories',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subcategory', to='adminpanel.ServiceCategories'),
        ),
    ]
